#!/usr/bin/env perl
use Mojolicious::Lite;
use lib'./lib';
use nukaduke;
use Data::Dumper;


get '/' => sub {
  my $self = shift;
  my $nukadoko = lookin('./nukadoko.yaml');
  $self->stash(entries => $nukadoko);
  $self->render('index');
};

post '/pickle' => sub {
  my $self = shift;
  my @params = $self->param;
  if ($params[0] =~ /^(.+)\.x$/){
    pickle('./nukadoko.yaml',$1)
  }
  $self->redirect_to('/');
};

post '/takeout' => sub {
  my $self = shift;
  my @params = $self->param('nukadoko');
  my $old_nukadoko = lookin('./nukadoko.yaml');
  splice @$old_nukadoko, $params[0], 1;
  takeout('./nukadoko.yaml', $old_nukadoko);
  $self->redirect_to('/');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title '俺のぬか漬';
<h1>俺のぬか漬</h1>
<h2>漬ける!</h2>
<div>
  <form action="/pickle" method="post" name="pickle">
    <p>
      <input type="image" src="/kyuuri.png" alt="kyuuri" name="kyuuri">
      <input type="image" src="/nasu.png" alt="nasu" name="nasu">
      <input type="image" src="/nagaimo.png" alt="nagaimo" name="nagaimo">
    </p>
  </form>
</div>
<br>
<br>
<HR>
<h2>now nukaduke'ing</h2>
<table>
  <tr>
% my $i = 0;
% for my $entry (@$entries){
    <td>
%= $entry->{$i}->[1];
    </td>
% $i++;
% };
  </tr>
  <tr>
% my $j = 0;
% for my $entry (@$entries){
    <td>
% my $vegetable = $entry->{$j}->[0];
% if($vegetable eq 'kyuuri'){
      <img src="/kyuuri_p.png">
% }elsif($vegetable eq 'nasu'){
      <img src="/nasu_p.png">
% }else{
      <img src="/nagaimo_p.png">
% };
    </td>
% $j++;
% };
  </tr>
</table>
<form action="/takeout" method="post" name="takeout">
  <select name="nukadoko">
% my $k = 0;
% for my $entry (@$entries){
    <option value= <%= $k %> >
%= $entry->{$k}->[0]." ".$entry->{$k}->[1]
    </option>
% $k++;
% };
  </select>
  <input type="submit" name="submit" value="取り出す">
</form>


@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
